name: NewRelease
on:
  push:
    branches:
      - dev
    paths:
      - 'GameModeManager/Plugin.cs'
jobs:
  NewRelease:
    if: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get Version Information
        id: version_info
        run: |
          echo "Getting current and previous version information..."

          CURRENT_MODULE_VERSION=$(grep -oP 'ModuleVersion => "\K[^"]+' GameModeManager/Plugin.cs)
          echo "current_module_version=$CURRENT_MODULE_VERSION" >> $GITHUB_ENV

          PREVIOUS_MODULE_VERSION=$(git show HEAD~1:GameModeManager/Plugin.cs | grep -oP 'ModuleVersion => "\K[^"]+' GameModeManager/Plugin.cs)
          echo "previous_module_version=$PREVIOUS_MODULE_VERSION" >> $GITHUB_ENV

          CURRENT_CONFIG_VERSION=$(grep -oP 'public int Version { get; set; } = \K\d+' GameModeManager/Config.cs)
          echo "current_config_version=$CURRENT_CONFIG_VERSION" >> $GITHUB_ENV

          PREVIOUS_CONFIG_VERSION=$(git show HEAD~1:GameModeManager/Config.cs | grep -oP 'public int Version { get; set; } = \K\d+' GameModeManager/Config.cs)
          echo "previous_config_version=$PREVIOUS_CONFIG_VERSION" >> $GITHUB_ENV

      - name: Check for Version Changes
        id: check_version_change
        run: |
          MODULE_VERSION_CHANGED="false"
          CONFIG_VERSION_CHANGED="false"

          if [[ "${{ env.current_module_version }}" != "${{ env.previous_module_version }}" ]]; then
            MODULE_VERSION_CHANGED="true"
          fi
          echo "module_version_changed=$MODULE_VERSION_CHANGED" >> $GITHUB_ENV

          if [[ "${{ env.current_config_version }}" != "${{ env.previous_config_version }}" ]]; then
            CONFIG_VERSION_CHANGED="true"
          fi
          echo "config_version_changed=$CONFIG_VERSION_CHANGED" >> $GITHUB_ENV

      - name: Get Commit History
        if: ${{ env.module_version_changed == 'true' }}
        id: get_commit_history
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null) || LAST_TAG=$(git rev-list --max-parents=0 HEAD) # Fallback to first commit if no tags
          COMMIT_HISTORY=$(git log --pretty=format:"%s" "$LAST_TAG"..HEAD)
          echo "commit_history=$(echo "$COMMIT_HISTORY" | jq -sRr @uri)" >> $GITHUB_ENV

      - name: Parse Commit History
        if: ${{ env.module_version_changed == 'true' }}
        id: parse_commits
        run: |
          COMMIT_HISTORY="${{ steps.get_commit_history.outputs.commit_history }}"
          FEATURES=""
          BUG_FIXES=""
          MISC=""

          IFS=$'\n'
          for COMMIT in $(echo "$COMMIT_HISTORY"); do
            case "$COMMIT" in
              ADDED:*|Added:*)
                FEATURES="$FEATURES- $(echo "$COMMIT" | cut -d':' -f2-)\n"
                ;;
              Fix:*|Bug:*|BugFix:*)
                # Capture the "Thanks" and issue number if present
                THANKS=$(echo "$COMMIT" | grep -oE 'Thanks\s+@\w+\s+#\d+')
                MESSAGE=$(echo "$COMMIT" | sed -E 's/Fix:|Bug:|BugFix://i' | sed -E 's/Thanks\s+@\w+\s+#\d+//')
                BUG_FIXES="$BUG_FIXES- $(echo "$MESSAGE" | sed -e 's/^[[:space:]]*//') $THANKS\n"
                ;;
              *)
                MISC="$MISC- $COMMIT\n"
                ;;
            esac
          done

          if [[ -n "$FEATURES" ]]; then
            echo "features=$FEATURES" >> $GITHUB_ENV
          fi
          if [[ -n "$BUG_FIXES" ]]; then
            echo "bug_fixes=$BUG_FIXES" >> $GITHUB_ENV
          fi
          if [[ -n "$MISC" ]]; then
            echo "misc=$MISC" >> $GITHUB_ENV
          fi

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore GameModeManager.sln

      - name: Build solution
        run: dotnet build --configuration Debug GameModeManager.sln

      - name: Create ZIP archive
        if: ${{ env.module_version_changed == 'true' }}
        run: |
          cd bin/Debug/net8.0/Public
          zip -r ../../../GameModeManager_v${{ env.current_module_version }}.zip .

      - name: Create Release
        uses: actions/create-release@v1.1.4
        if: ${{ env.module_version_changed == 'true' }}
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ env.current_module_version }}
          release_name: Game Mode Manager v${{ env.current_module_version }}
          body: |
            # Game Mode Manager v${{ env.current_module_version }}
            ${{ env.config_version_changed == 'true' && '> [!IMPORTANT]
            > - If moving from v${{ env.previous_module_version }} or earlier, back up your `GameModeManager.json` configuration file and let the plugin generate the new version. This version has minor changes to the configuration file.
            >' || '' }}

            ${{ env.features && '## Features' || '' }}
            ${{ env.features }}

            ${{ env.bug_fixes && '## Bug Fixes' || '' }}
            ${{ env.bug_fixes }}

            ${{ env.misc && '## Misc' || '' }}
            ${{ env.misc }}

            ## Installation
            1. Install Metamod:Source and Counter Strike Sharp.
            2. Copy `addons` and `cfg` folders to `/csgo/`.
            3. Make sure your `gamemodes_server.txt` or custom map group file is in [VDF Format](https://developer.valvesoftware.com/wiki/VDF) and contains a list of map groups.
            5. Update each game mode configuration file (i.e. comp.cfg) to include `css_gamemode <mode>`.
            6. After the first run, update the configuration file `GameModeManager.json`.

            For more information on the configuration of these features, please see the updated [README.md](https://github.com/nickj609/GameModeManager/blob/main/README.md).

            **Full Changelog**: https://github.com/nickj609/GameModeManager/compare/v${{ env.previous_module_version }}...v${{ env.current_module_version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: ${{ env.module_version_changed == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: GameModeManager_v${{ env.current_module_version }}.zip
          asset_name: GameModeManager_v${{ env.current_module_version }}.zip
          asset_content_type: application/zip
