name: Publish
on:
  push:
    branches:
      - dev
    paths:
      - 'GameModeManager/Plugin.cs'
jobs:
  NewRelease:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version Information
        id: version_info
        run: |
          echo "Getting current and previous version information..."
          current_module_version=$(grep -oP 'ModuleVersion => "\K[^"]+' GameModeManager/Plugin.cs)
          echo "current_module_version=$current_module_version" >> $GITHUB_OUTPUT
          previous_module_version=$(git show HEAD~1:GameModeManager/Plugin.cs | grep -oP 'ModuleVersion => "\K[^"]+')
          echo "previous_module_version=$previous_module_version" >> $GITHUB_OUTPUT
          current_config_version=$(grep -oP 'public int Version { get; set; } = \K\d+' GameModeManager/Config.cs)
          echo "current_config_version=$current_config_version" >> $GITHUB_OUTPUT
          previous_config_version=$(git show HEAD~1:GameModeManager/Config.cs | grep -oP 'public int Version { get; set; } = \K\d+' GameModeManager/Config.cs)
          echo "previous_config_version=$previous_config_version" >> $GITHUB_OUTPUT

      - name: Check for Version Changes
        id: check_version_change
        run: |
          module_version_changed="false"
          config_version_changed="false"
          if [[ "${{ steps.version_info.outputs.current_module_version }}" != "${{ steps.version_info.outputs.previous_module_version }}" ]]; then
            module_version_changed="true"
          fi
          echo "module_version_changed=$module_version_changed" >> $GITHUB_OUTPUT
          if [[ "${{ steps.version_info.outputs.current_config_version }}" != "${{ steps.version_info.outputs.previous_config_version }}" ]]; then
            config_version_changed="true"
          fi
          echo "config_version_changed=$config_version_changed" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore GameModeManager.sln

      - name: Build solution
        run: dotnet build --configuration Debug GameModeManager.sln

      - name: Create ZIP archive
        if: ${{ steps.check_version_change.outputs.module_version_changed == 'true' }}
        run: |
          cd bin/Debug/net8.0/Public
          zip -r GameModeManager_v${{ steps.version_info.outputs.current_module_version }}.zip ./*

      - name: Create Release
        if: ${{ steps.check_version_change.outputs.module_version_changed == 'true' }}
        id: create_release
        uses: softprops/action-gh-release@v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version_info.outputs.current_module_version }}
          name: Release Game Mode Manager v${{ steps.version_info.outputs.current_module_version }}
          body: |
            # Game Mode Manager v${{ steps.version_info.outputs.current_module_version }}
            ${{ steps.check_version_change.outputs.config_version_changed == 'true' && '> [!IMPORTANT]
            > - If moving from v${{ steps.version_info.outputs.previous_module_version }} or earlier, back up your `GameModeManager.json` configuration file and let the plugin generate the new version. This version has minor changes to the configuration file.
            >' || '' }}
          append_body: |
            ## Installation
            1. Install Metamod:Source and Counter Strike Sharp.
            2. Copy `addons` and `cfg` folders to `/csgo/`.
            3. Make sure your `gamemodes_server.txt` or custom map group file is in [VDF Format](https://developer.valvesoftware.com/wiki/VDF) and contains a list of map groups.
            5. Update each game mode configuration file (i.e. comp.cfg) to include `css_gamemode <mode>`.
            6. After the first run, update the configuration file `GameModeManager.json`.
            For more information on the configuration of these features, please see the updated [README.md](https://github.com/nickj609/GameModeManager/blob/main/README.md).
            **Full Changelog**: https://github.com/nickj609/GameModeManager/compare/v${{ steps.version_info.outputs.previous_module_version }}...v${{ steps.version_info.outputs.current_module_version }}
          draft: false
          prerelease: false
          generate_release_notes: true
      - name: Upload Release Asset
        if: ${{ steps.check_version_change.outputs.module_version_changed == 'true'}}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/Debug/net8.0/Public/GameModeManager_v${{ steps.version_info.outputs.current_module_version }}.zip
          asset_name: GameModeManager_v${{ steps.version_info.outputs.current_module_version }}.zip
          asset_content_type: application/zip